"""Add cat, lic_no, distance_km, and race_year to table

Revision ID: 245d4da5b9e4
Revises: 
Create Date: 2020-03-19 19:47:37.347953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d4da5b9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'sex')
    # ### end Alembic commands ###
