"""Change column distance_bin to distance_cat

Revision ID: 2524785502b4
Revises: c137e7385dd7
Create Date: 2020-03-20 16:47:15.648707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2524785502b4'
down_revision = 'c137e7385dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('distance_cat', sa.String(), nullable=True))
    op.create_foreign_key(None, 'race', 'runner_contact', ['runner_contact_id'], ['id'])
    op.drop_column('race', 'distance_bin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('distance_bin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column('race', 'distance_cat')
    # ### end Alembic commands ###
